// Generated by ReScript, PLEASE EDIT WITH CARE


function parseAttrs(node) {
  var match = node.type;
  if (match === "input") {
    return /* UiNodeInputAttributes */{
            _0: {
              disabled: node.attributes.disabled,
              label: node.attributes.label,
              name: node.attributes.name,
              pattern: node.attributes.pattern,
              required: node.attributes.required,
              type: node.attributes.type,
              value: node.attributes.value
            }
          };
  } else {
    return /* UiNodeNotRecognized */3;
  }
}

export {
  parseAttrs ,
  
}
/* No side effect */
