// Generated by ReScript, PLEASE EDIT WITH CARE


var Unsafe = {};

function redirect(url) {
  var loc = typeof location === "undefined" ? undefined : location;
  if (loc !== undefined) {
    loc.href = url;
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: /* ErrorObjectNotFound */{
              _0: "Location object not found in global namespac."
            }
          };
  }
}

export {
  Unsafe ,
  redirect ,
  
}
/* No side effect */
