CREATE USER kratos;
CREATE USER keto;
CREATE USER shorts;

CREATE DATABASE kratos;
CREATE DATABASE keto;
CREATE DATABASE shorts;

GRANT ALL PRIVILEGES ON DATABASE kratos TO kratos;
GRANT ALL PRIVILEGES ON DATABASE keto TO keto;
GRANT ALL PRIVILEGES ON DATABASE shorts TO shorts;
