version: '3.7'

services:
  envoy:
    image: envoyproxy/envoy-dev:e07746c5100da110754bcf83940a254025e65e54
    ports:
      - '8000:10000'
      - '9901:9901'
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  hello:
    build:
      context: 'hello'
    networks:
      - intranet

  postgres-kratos:
    extends:
      file: ../../_common/docker-compose.yml
      service: postgres-kratos

  kratos-migrate:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos-migrate

  kratos:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos

  kratos-selfservice-ui-node:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos-selfservice-ui-node

  mailslurper:
    extends:
      file: ../../_common/docker-compose.yml
      service: mailslurper

networks:
  intranet:
