// Generated by ReScript, PLEASE EDIT WITH CARE


var Registration = {
  title: "Registration",
  submitButtonLabel: "Registration"
};

var Login = {
  title: "Sign in",
  submitButtonLabel: "Sign in",
  forgotPasswordLabel: "Forgot your password?"
};

var Recovery = {
  title: "Recover Password"
};

export {
  Registration ,
  Login ,
  Recovery ,
  
}
/* No side effect */
