// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NotFound(Props) {
  return React.createElement("div", undefined, "NOT FOUND");
}

var make = NotFound;

export {
  make ,
  
}
/* react Not a pure module */
