// Generated by ReScript, PLEASE EDIT WITH CARE


var dashboard = "/";

var login = "/login";

var register = "/register";

var recovery = "/recovery";

export {
  dashboard ,
  login ,
  register ,
  recovery ,
  
}
/* No side effect */
