version: '3.7'
services:
  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet
  kratos-migrate:
    depends_on:
      - postgresd
    image: oryd/kratos:v0.8.0-alpha.3
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ${PWD}/kratos/configs
        target: /etc/config/kratos
    command: ["migrate", "sql", "--read-from-env", "--config", "/etc/config/kratos/kratos.yaml", "--yes"]
    networks:
      - intranet
  kratos:
    depends_on:
        - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.3
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    volumes:
      -
        type: bind
        source: ${PWD}/kratos/configs
        target: /etc/config/kratos
    ports:
      - 4434:4434
      - 4433:4433
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
networks:
  intranet:
