version: "2.4"

services:

  ory-hydra-oauth2-example-pgadmin:
    image: dpage/pgadmin4:7.3
    container_name: ory-hydra-oauth2-example-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

    restart: unless-stopped
    ports:
      - 9245:80
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    mem_limit: 256M
    depends_on:
      ory-hydra-oauth2-ex-auth-server-userdata-postgresql:
        condition: service_healthy
      ory-hydra-oauth2-ex-auth-server-hydradata-postgresql:
        condition: service_healthy
    networks:
      - app-network

  ory-hydra-oauth2-example-authorization-server-backend:
    image: chistousov/ory-hydra-oauth2-example-authorization-server-backend:1.0.0
    container_name: ory-hydra-oauth2-example-authorization-server-backend
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en

      - BPL_JAVA_NMT_LEVEL=detail

      # health check
      - THC_PATH=/actuator/health
      - THC_PORT=8090

      - JAVA_TOOL_OPTIONS=
        -Dspring.profiles.active=prod
        
        -Dspring.datasource.driverClassName=org.postgresql.Driver
        -Dspring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
        -Dspring.datasource.url=jdbc:postgresql://user-data-postgresql:5432/user_data?user=user_data&password=${USER_DATA_POSTGRESQL_PASSWORD}&escapeSyntaxCallMode=callIfNoReturn
    
        -Dapplication.ory-hydra.admin.baseURI=http://ory-hydra-oauth2-example-authorization-server-hydra:4445/admin/

        -Dapplication.ory-hydra.number-of-login-attempts=3

        -Dapplication.ory-hydra.frontend.login-redirectURI=/login

        -Dapplication.ory-hydra.frontend.consent-redirectURI=/consent

        -Dapplication.ory-hydra.frontend.logout-redirectURI=/logout/request
        -Dapplication.ory-hydra.frontend.logout-cancel-redirectURI=/logout/cancel

    user: "1005"
    mem_limit: 1G
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    healthcheck:
      test: "/cnb/process/health-check"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      ory-hydra-oauth2-ex-auth-server-userdata-postgresql:
        condition: service_healthy
      ory-hydra-oauth2-example-authorization-server-hydra:
        condition: service_started
    networks:
      - app-network

  ory-hydra-oauth2-example-authorization-server-frontend:
    image: chistousov/ory-hydra-oauth2-example-authorization-server-frontend:1.0.0
    container_name: ory-hydra-oauth2-example-authorization-server-frontend
    environment:

      # health check
      - THC_PATH=/health
      - THC_PORT=4000

    user: "1005"
    mem_limit: 512M
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    healthcheck:
      test: "/cnb/process/health-check"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      ory-hydra-oauth2-example-authorization-server-backend:
        condition: service_healthy
    networks:
      - app-network

  ory-hydra-oauth2-example-gateway-nginx:
    image: nginx:1.25.3-bookworm
    container_name: ory-hydra-oauth2-example-gateway-nginx
    healthcheck:
      test: '[ -e /var/run/nginx.pid ] || exit 1'
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    ports:
      - 443:443
    volumes:
      - type: bind
        source: nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: nginx/confs
        target: /etc/nginx/conf.d
        read_only: true

      - type: bind
        source: nginx/cert
        target: /cert
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

    restart: unless-stopped
    depends_on:
      ory-hydra-oauth2-example-authorization-server-backend:
        condition: service_healthy
      ory-hydra-oauth2-example-authorization-server-frontend:
        condition: service_healthy
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    mem_limit: 1G
    networks:
      - app-network