// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as ReactDom from "react-dom";

import './styles/main.css'
;

var element = document.querySelector("#root");

if (!(element == null)) {
  ReactDom.render(React.createElement(App.make, {}), element);
}

export {
  
}
/*  Not a pure module */
