// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ActionMessages(Props) {
  var messages = Props.messages;
  return messages.map(function (m) {
              var match = m.type;
              var classes = match === "error" ? "flex justify-center items-center m-1 font-small py-1 px-2 bg-white rounded-md text-red-700 bg-red-100 border border-red-300" : "flex justify-center items-center m-1 font-small py-1 px-2 bg-white rounded-md text-green-700 bg-green-100 border border-green-300";
              return React.createElement("p", {
                          key: String(m.id),
                          className: classes
                        }, m.text);
            });
}

var make = ActionMessages;

export {
  make ,
  
}
/* react Not a pure module */
