// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Kratos from "../Bindings/Kratos.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DynamicInput from "./DynamicInput.mjs";

function DynamicInputList(Props) {
  var nodes = Props.nodes;
  return nodes.map(function (node, i) {
              var attrs = Kratos.parseAttrs(node);
              if (typeof attrs === "number") {
                return null;
              }
              var attrs$1 = attrs._0;
              var tmp = {
                name: attrs$1.name,
                type: attrs$1.type,
                required: Belt_Option.getWithDefault(attrs$1.required, false),
                key: String(i)
              };
              if (node.meta.label !== undefined) {
                tmp.label = Caml_option.valFromOption(node.meta.label);
              }
              if (attrs$1.value !== undefined) {
                tmp.value = Caml_option.valFromOption(attrs$1.value);
              }
              var tmp$1 = Caml_option.nullable_to_opt(node.messages);
              if (tmp$1 !== undefined) {
                tmp.messages = Caml_option.valFromOption(tmp$1);
              }
              return React.createElement(DynamicInput.make, tmp);
            });
}

var make = DynamicInputList;

export {
  make ,
  
}
/* react Not a pure module */
